import aima3.utils

def getClausses():
    clausses = []
    # clausulas del usuario a BC
    clausses.append(aima3.utils.expr("Lenguaje(x) ==> LengUser(x)"))
    clausses.append(aima3.utils.expr("Framework(x) ==> FrameUser(x)"))
    clausses.append(aima3.utils.expr("Experiencia(x) ==> ExpLengUser(x)"))
    clausses.append(aima3.utils.expr("Experiencia(x) ==> ExpFrameUser(x)"))
    #-------------------
    clausses.append(aima3.utils.expr("Orientacionuser(Frontend) & ExpFrameUser(Junior) ==> Puesto(Frontend)"))
    clausses.append(aima3.utils.expr("Puesto(Backend)"))
    clausses.append(aima3.utils.expr("Puesto(Fullstack)"))
    clausses.append(aima3.utils.expr("Puesto(DBA)"))
    clausses.append(aima3.utils.expr("Puesto(TeamLeader)"))
    clausses.append(aima3.utils.expr("Puesto(SoftwareEngineerManager)"))
    clausses.append(aima3.utils.expr("Puesto(ChiefTechnologyOfficer)"))
    clausses.append(aima3.utils.expr("Puesto(CTO)"))
    #-------------------
    clausses.append(aima3.utils.expr("Lenguaje(Python)"))
    clausses.append(aima3.utils.expr("Lenguaje(Java)"))
    # clauses.append(aima3.utils.expr("Lenguaje(C++)"))
    clausses.append(aima3.utils.expr("Lenguaje(Ruby)"))
    clausses.append(aima3.utils.expr("Lenguaje(Swift)"))
    clausses.append(aima3.utils.expr("Lenguaje(Go)"))
    clausses.append(aima3.utils.expr("Lenguaje(Rust)"))
    clausses.append(aima3.utils.expr("Lenguaje(PHP)"))
    clausses.append(aima3.utils.expr("Lenguaje(Haskell)"))
    # clauses.append(aima3.utils.expr("Lenguaje(C#)"))
    clausses.append(aima3.utils.expr("Lenguaje(Perl)"))
    clausses.append(aima3.utils.expr("Lenguaje(Objective-C)"))
    clausses.append(aima3.utils.expr("Lenguaje(Kotlin)"))
    clausses.append(aima3.utils.expr("Lenguaje(Scala)"))
    clausses.append(aima3.utils.expr("Lenguaje(R)"))
    clausses.append(aima3.utils.expr("Lenguaje(Lua)"))
    clausses.append(aima3.utils.expr("Lenguaje(Matlab)"))
    clausses.append(aima3.utils.expr("Lenguaje(Groovy)"))
    clausses.append(aima3.utils.expr("Lenguaje(Clojure)"))
    clausses.append(aima3.utils.expr("Lenguaje(Shell)"))
    clausses.append(aima3.utils.expr("Lenguaje(Assembly)"))
    # clauses.append(aima3.utils.expr("Lenguaje(F#)"))
    clausses.append(aima3.utils.expr("Lenguaje(Elixir)"))
    clausses.append(aima3.utils.expr("Lenguaje(Julia)"))
    clausses.append(aima3.utils.expr("Lenguaje(Racket)"))
    clausses.append(aima3.utils.expr("Lenguaje(Fortran)"))
    # clauses.append(aima3.utils.expr("Lenguaje(VB.NET)"))
    # clauses.append(aima3.utils.expr("Lenguaje(.Net)"))
    clausses.append(aima3.utils.expr("Lenguaje(JavaScript)"))
    clausses.append(aima3.utils.expr("Lenguaje(TypeScript)"))
    clausses.append(aima3.utils.expr("Lenguaje(HTML)"))
    clausses.append(aima3.utils.expr("Lenguaje(CSS)"))
    clausses.append(aima3.utils.expr("Lenguaje(Dart)"))
    clausses.append(aima3.utils.expr("Lenguaje(MySQL)"))
    clausses.append(aima3.utils.expr("Lenguaje(MongoDB)"))
    clausses.append(aima3.utils.expr("Lenguaje(MariaDB)"))
    clausses.append(aima3.utils.expr("Lenguaje(Sql)"))

    clausses.append(aima3.utils.expr("Framework(React)"))
    clausses.append(aima3.utils.expr("Framework(Angular)"))
    # clauses.append(aima3.utils.expr("Framework(Vue.js)"))
    clausses.append(aima3.utils.expr("Framework(Django)"))
    clausses.append(aima3.utils.expr("Framework(RubyonRails)"))
    clausses.append(aima3.utils.expr("Framework(Laravel)"))
    clausses.append(aima3.utils.expr("Framework(Spring)"))
    # clauses.append(aima3.utils.expr("Framework(Express.js)"))
    # clauses.append(aima3.utils.expr("Framework(ASP.NET)"))
    clausses.append(aima3.utils.expr("Framework(Flask)"))
    clausses.append(aima3.utils.expr("Framework(Symfony)"))
    # clauses.append(aima3.utils.expr("Framework(ASP.NETCore)"))
    clausses.append(aima3.utils.expr("Framework(Flutter)"))
    # clauses.append(aima3.utils.expr("Framework(Ember.js)"))
    # clauses.append(aima3.utils.expr("Framework(Xamarin)"))
    # clauses.append(aima3.utils.expr("Framework(Backbone.js)"))
    clausses.append(aima3.utils.expr("Framework(Meteor)"))
    clausses.append(aima3.utils.expr("Framework(PlayFramework)"))
    clausses.append(aima3.utils.expr("Framework(CakePHP)"))
    clausses.append(aima3.utils.expr("Framework(CodeIgniter)"))
    clausses.append(aima3.utils.expr("Framework(PlayFramework)"))
    clausses.append(aima3.utils.expr("Framework(Angular)"))
    # clauses.append(aima3.utils.expr("Framework(Express.js)"))
    # clauses.append(aima3.utils.expr("Framework(ASP.NET)"))


    clausses.append(aima3.utils.expr("Utiliza(Angular,JavaScript)"))
    clausses.append(aima3.utils.expr("Utiliza(Angular,TypeScript)"))
    # clauses.append(aima3.utils.expr("Utiliza(ASP.NET,C#)"))
    # clauses.append(aima3.utils.expr("Utiliza(ASP.NET,VB.NET)"))
    # clauses.append(aima3.utils.expr("Utiliza(ASP.NETCore,C#)"))
    # clauses.append(aima3.utils.expr("Utiliza(Backbone.js,JavaScript)"))
    clausses.append(aima3.utils.expr("Utiliza(CakePHP,PHP)"))
    clausses.append(aima3.utils.expr("Utiliza(CodeIgniter,PHP)"))
    clausses.append(aima3.utils.expr("Utiliza(Django,Python)"))
    # clauses.append(aima3.utils.expr("Utiliza(Ember.js,JavaScript)"))
    # clauses.append(aima3.utils.expr("Utiliza(Express.js,JavaScript)"))
    # clauses.append(aima3.utils.expr("Utiliza(Express.js,Node.js)"))
    clausses.append(aima3.utils.expr("Utiliza(Flask,Python)"))
    clausses.append(aima3.utils.expr("Utiliza(Flutter,Dart)"))
    clausses.append(aima3.utils.expr("Utiliza(Laravel,PHP)"))
    clausses.append(aima3.utils.expr("Utiliza(Meteor,JavaScript)"))
    clausses.append(aima3.utils.expr("Utiliza(PlayFramework,Java)"))
    clausses.append(aima3.utils.expr("Utiliza(PlayFramework,Scala)"))
    clausses.append(aima3.utils.expr("Utiliza(React,JavaScript)"))
    clausses.append(aima3.utils.expr("Utiliza(RubyonRails,Ruby)"))
    clausses.append(aima3.utils.expr("Utiliza(Spring,Java)"))
    clausses.append(aima3.utils.expr("Utiliza(Symfony,PHP)"))
    # clauses.append(aima3.utils.expr("Utiliza(Vue.js,JavaScript)"))
    # clauses.append(aima3.utils.expr("Utiliza(Xamarin,C#)"))
    #-------------------
    clausses.append(aima3.utils.expr("Orientacion(Backend)"))
    clausses.append(aima3.utils.expr("Orientacion(Frontend)"))
    clausses.append(aima3.utils.expr("Orientacion(Dba)"))
    #-------------------
    clausses.append(aima3.utils.expr("LengOrientado(Python,Backend)"))
    clausses.append(aima3.utils.expr("LengOrientado(Java,Backend)"))
    # clauses.append(aima3.utils.expr("LengOrientado(C++,Backend)"))
    clausses.append(aima3.utils.expr("LengOrientado(Ruby,Backend)"))
    clausses.append(aima3.utils.expr("LengOrientado(Swift,Backend)"))
    clausses.append(aima3.utils.expr("LengOrientado(Go,Backend)"))
    clausses.append(aima3.utils.expr("LengOrientado(Rust,Backend)"))
    clausses.append(aima3.utils.expr("LengOrientado(PHP,Backend)"))
    clausses.append(aima3.utils.expr("LengOrientado(Haskell,Backend)"))
    # clauses.append(aima3.utils.expr("LengOrientado(C#,Backend)"))
    clausses.append(aima3.utils.expr("LengOrientado(Perl,Backend)"))
    clausses.append(aima3.utils.expr("LengOrientado(Objective-C,Backend)"))
    clausses.append(aima3.utils.expr("LengOrientado(Kotlin,Backend)"))
    clausses.append(aima3.utils.expr("LengOrientado(Scala,Backend)"))
    clausses.append(aima3.utils.expr("LengOrientado(R,Backend)"))
    clausses.append(aima3.utils.expr("LengOrientado(Lua,Backend)"))
    clausses.append(aima3.utils.expr("LengOrientado(Matlab,Backend)"))
    clausses.append(aima3.utils.expr("LengOrientado(Groovy,Backend)"))
    clausses.append(aima3.utils.expr("LengOrientado(Clojure,Backend)"))
    clausses.append(aima3.utils.expr("LengOrientado(Shell,Backend)"))
    clausses.append(aima3.utils.expr("LengOrientado(MySQL,Backend)"))
    clausses.append(aima3.utils.expr("LengOrientado(MongoDB,Backend)"))
    clausses.append(aima3.utils.expr("LengOrientado(mariaDB,Backend)"))
    clausses.append(aima3.utils.expr("LengOrientado(Sql,Backend)"))
    clausses.append(aima3.utils.expr("LengOrientado(Assembly,Backend)"))
    # clauses.append(aima3.utils.expr("LengOrientado(F#,Backend)"))
    clausses.append(aima3.utils.expr("LengOrientado(Elixir,Backend)"))
    clausses.append(aima3.utils.expr("LengOrientado(Julia,Backend)"))
    clausses.append(aima3.utils.expr("LengOrientado(Racket,Backend)"))
    clausses.append(aima3.utils.expr("LengOrientado(Fortran,Backend)"))
    # clauses.append(aima3.utils.expr("LengOrientado(VB.NET,Backend)"))
    # clauses.append(aima3.utils.expr("LengOrientado(.Net,Backend)"))
    clausses.append(aima3.utils.expr("LengOrientado(JavaScript,Frontend)"))
    clausses.append(aima3.utils.expr("LengOrientado(TypeScript,Frontend)"))
    clausses.append(aima3.utils.expr("LengOrientado(HTML,Frontend)"))
    clausses.append(aima3.utils.expr("LengOrientado(CSS,Frontend)"))
    clausses.append(aima3.utils.expr("LengOrientado(Dart,Frontend)"))
    #-------------------
    clausses.append(aima3.utils.expr("Pais(EstadosUnidos)"))
    clausses.append(aima3.utils.expr("Pais(Argentina)"))
    clausses.append(aima3.utils.expr("Pais(Brasil)"))
    clausses.append(aima3.utils.expr("Pais(Uruguay)"))
    clausses.append(aima3.utils.expr("Pais(Paraguay)"))
    clausses.append(aima3.utils.expr("Pais(Chile)"))
    clausses.append(aima3.utils.expr("Pais(Bolivia)"))
    clausses.append(aima3.utils.expr("Pais(México)"))
    clausses.append(aima3.utils.expr("Pais(Inglaterra)"))
    clausses.append(aima3.utils.expr("Pais(Francia)"))
    clausses.append(aima3.utils.expr("Pais(Alemania)"))
    #-------------------
    clausses.append(aima3.utils.expr("Ciudad(Berlín)"))
    clausses.append(aima3.utils.expr("Ciudad(Múnich)"))
    clausses.append(aima3.utils.expr("Ciudad(Hamburgo)"))
    clausses.append(aima3.utils.expr("Ciudad(Fráncfort)"))
    clausses.append(aima3.utils.expr("Ciudad(Colonia)"))
    clausses.append(aima3.utils.expr("Ciudad(BuenosAires)"))
    clausses.append(aima3.utils.expr("Ciudad(Córdoba)"))
    clausses.append(aima3.utils.expr("Ciudad(Rosario)"))
    clausses.append(aima3.utils.expr("Ciudad(Mendoza)"))
    clausses.append(aima3.utils.expr("Ciudad(MardelPlata)"))
    clausses.append(aima3.utils.expr("Ciudad(LaPaz)"))
    clausses.append(aima3.utils.expr("Ciudad(SantaCruzdelaSierra)"))
    clausses.append(aima3.utils.expr("Ciudad(Cochabamba)"))
    clausses.append(aima3.utils.expr("Ciudad(Sucre)"))
    clausses.append(aima3.utils.expr("Ciudad(Potosí)"))
    clausses.append(aima3.utils.expr("Ciudad(SãoPaulo)"))
    clausses.append(aima3.utils.expr("Ciudad(RíodeJaneiro)"))
    clausses.append(aima3.utils.expr("Ciudad(Brasilia)"))
    clausses.append(aima3.utils.expr("Ciudad(Salvador)"))
    clausses.append(aima3.utils.expr("Ciudad(BeloHorizonte)"))
    clausses.append(aima3.utils.expr("Ciudad(Santiago)"))
    clausses.append(aima3.utils.expr("Ciudad(Valparaíso)"))
    clausses.append(aima3.utils.expr("Ciudad(ViñadelMar)"))
    clausses.append(aima3.utils.expr("Ciudad(Concepción)"))
    clausses.append(aima3.utils.expr("Ciudad(LaSerena)"))
    clausses.append(aima3.utils.expr("Ciudad(NuevaYork)"))
    clausses.append(aima3.utils.expr("Ciudad(LosÁngeles)"))
    clausses.append(aima3.utils.expr("Ciudad(Chicago)"))
    clausses.append(aima3.utils.expr("Ciudad(Miami)"))
    clausses.append(aima3.utils.expr("Ciudad(SanFrancisco)"))
    clausses.append(aima3.utils.expr("Ciudad(Paris)"))
    clausses.append(aima3.utils.expr("Ciudad(Marsella)"))
    clausses.append(aima3.utils.expr("Ciudad(Lyon)"))
    clausses.append(aima3.utils.expr("Ciudad(Toulouse)"))
    clausses.append(aima3.utils.expr("Ciudad(Niza)"))
    clausses.append(aima3.utils.expr("Ciudad(Londres)"))
    clausses.append(aima3.utils.expr("Ciudad(Manchester)"))
    clausses.append(aima3.utils.expr("Ciudad(Birmingham)"))
    clausses.append(aima3.utils.expr("Ciudad(Liverpool)"))
    clausses.append(aima3.utils.expr("Ciudad(Bristol)"))
    clausses.append(aima3.utils.expr("Ciudad(CiudaddeMéxico)"))
    clausses.append(aima3.utils.expr("Ciudad(Cancún)"))
    clausses.append(aima3.utils.expr("Ciudad(Guadalajara)"))
    clausses.append(aima3.utils.expr("Ciudad(Monterrey)"))
    clausses.append(aima3.utils.expr("Ciudad(Tijuana)"))
    clausses.append(aima3.utils.expr("Ciudad(Asunción)"))
    clausses.append(aima3.utils.expr("Ciudad(CiudaddelEste)"))
    clausses.append(aima3.utils.expr("Ciudad(Encarnación)"))
    clausses.append(aima3.utils.expr("Ciudad(Luque)"))
    clausses.append(aima3.utils.expr("Ciudad(SanLorenzo)"))
    clausses.append(aima3.utils.expr("Ciudad(Montevideo)"))
    clausses.append(aima3.utils.expr("Ciudad(PuntadelEste)"))
    clausses.append(aima3.utils.expr("Ciudad(ColoniadelSacramento)"))
    clausses.append(aima3.utils.expr("Ciudad(Salto)"))
    clausses.append(aima3.utils.expr("Ciudad(Piriápolis)"))
    #-------------------
    clausses.append(aima3.utils.expr("CiudadPais(Berlín,Alemania)"))
    clausses.append(aima3.utils.expr("CiudadPais(Múnich,Alemania)"))
    clausses.append(aima3.utils.expr("CiudadPais(Hamburgo,Alemania)"))
    clausses.append(aima3.utils.expr("CiudadPais(Fráncfort,Alemania)"))
    clausses.append(aima3.utils.expr("CiudadPais(Colonia,Alemania)"))
    clausses.append(aima3.utils.expr("CiudadPais(BuenosAires,Argentina)"))
    clausses.append(aima3.utils.expr("CiudadPais(Córdoba,Argentina)"))
    clausses.append(aima3.utils.expr("CiudadPais(Rosario,Argentina)"))
    clausses.append(aima3.utils.expr("CiudadPais(Mendoza,Argentina)"))
    clausses.append(aima3.utils.expr("CiudadPais(MardelPlata,Argentina)"))
    clausses.append(aima3.utils.expr("CiudadPais(LaPaz,Bolivia)"))
    clausses.append(aima3.utils.expr("CiudadPais(SantaCruzdelaSierra,Bolivia)"))
    clausses.append(aima3.utils.expr("CiudadPais(Cochabamba,Bolivia)"))
    clausses.append(aima3.utils.expr("CiudadPais(Sucre,Bolivia)"))
    clausses.append(aima3.utils.expr("CiudadPais(Potosí,Bolivia)"))
    clausses.append(aima3.utils.expr("CiudadPais(SãoPaulo,Brasil)"))
    clausses.append(aima3.utils.expr("CiudadPais(RíodeJaneiro,Brasil)"))
    clausses.append(aima3.utils.expr("CiudadPais(Brasilia,Brasil)"))
    clausses.append(aima3.utils.expr("CiudadPais(Salvador,Brasil)"))
    clausses.append(aima3.utils.expr("CiudadPais(BeloHorizonte,Brasil)"))
    clausses.append(aima3.utils.expr("CiudadPais(Santiago,Chile)"))
    clausses.append(aima3.utils.expr("CiudadPais(Valparaíso,Chile)"))
    clausses.append(aima3.utils.expr("CiudadPais(ViñadelMar,Chile)"))
    clausses.append(aima3.utils.expr("CiudadPais(Concepción,Chile)"))
    clausses.append(aima3.utils.expr("CiudadPais(LaSerena,Chile)"))
    clausses.append(aima3.utils.expr("CiudadPais(NuevaYork,EstadosUnidos)"))
    clausses.append(aima3.utils.expr("CiudadPais(LosÁngeles,EstadosUnidos)"))
    clausses.append(aima3.utils.expr("CiudadPais(Chicago,EstadosUnidos)"))
    clausses.append(aima3.utils.expr("CiudadPais(Miami,EstadosUnidos)"))
    clausses.append(aima3.utils.expr("CiudadPais(SanFrancisco,EstadosUnidos)"))
    clausses.append(aima3.utils.expr("CiudadPais(Paris,Francia)"))
    clausses.append(aima3.utils.expr("CiudadPais(Marsella,Francia)"))
    clausses.append(aima3.utils.expr("CiudadPais(Lyon,Francia)"))
    clausses.append(aima3.utils.expr("CiudadPais(Toulouse,Francia)"))
    clausses.append(aima3.utils.expr("CiudadPais(Niza,Francia)"))
    clausses.append(aima3.utils.expr("CiudadPais(Londres,Inglaterra)"))
    clausses.append(aima3.utils.expr("CiudadPais(Manchester,Inglaterra)"))
    clausses.append(aima3.utils.expr("CiudadPais(Birmingham,Inglaterra)"))
    clausses.append(aima3.utils.expr("CiudadPais(Liverpool,Inglaterra)"))
    clausses.append(aima3.utils.expr("CiudadPais(Bristol,Inglaterra)"))
    clausses.append(aima3.utils.expr("CiudadPais(CiudaddeMéxico,Mexico)"))
    clausses.append(aima3.utils.expr("CiudadPais(Cancún,Mexico)"))
    clausses.append(aima3.utils.expr("CiudadPais(Guadalajara,Mexico)"))
    clausses.append(aima3.utils.expr("CiudadPais(Monterrey,Mexico)"))
    clausses.append(aima3.utils.expr("CiudadPais(Tijuana,Mexico)"))
    clausses.append(aima3.utils.expr("CiudadPais(Asunción,Paraguay)"))
    clausses.append(aima3.utils.expr("CiudadPais(CiudaddelEste,Paraguay)"))
    clausses.append(aima3.utils.expr("CiudadPais(Encarnación,Paraguay)"))
    clausses.append(aima3.utils.expr("CiudadPais(Luque,Paraguay)"))
    clausses.append(aima3.utils.expr("CiudadPais(SanLorenzo,Paraguay)"))
    clausses.append(aima3.utils.expr("CiudadPais(Montevideo,Uruguay)"))
    clausses.append(aima3.utils.expr("CiudadPais(PuntadelEste,Uruguay)"))
    clausses.append(aima3.utils.expr("CiudadPais(ColoniadelSacramento,Uruguay)"))
    clausses.append(aima3.utils.expr("CiudadPais(Salto,Uruguay)"))
    clausses.append(aima3.utils.expr("CiudadPais(Piriápolis,Uruguay)"))
    #-------------------
    clausses.append(aima3.utils.expr("Experiencia(Senior)"))
    clausses.append(aima3.utils.expr("Experiencia(Semi-senior)"))
    clausses.append(aima3.utils.expr("Experiencia(Junior)"))
    clausses.append(aima3.utils.expr("Experiencia(Pasante)"))
    #-------------------
    clausses.append(aima3.utils.expr("Idioma(Inglés)"))
    clausses.append(aima3.utils.expr("Idioma(Español)"))
    clausses.append(aima3.utils.expr("Idioma(Italiano)"))
    clausses.append(aima3.utils.expr("Idioma(Portugués)"))
    clausses.append(aima3.utils.expr("Idioma(Francés)"))
    clausses.append(aima3.utils.expr("Idioma(Alemán)"))
    #-------------------
    clausses.append(aima3.utils.expr("Modalidad(Presencial)"))
    clausses.append(aima3.utils.expr("Modalidad(Virtual)"))
    clausses.append(aima3.utils.expr("Modalidad(Mixta)"))
    #-------------------
    clausses.append(aima3.utils.expr("Disponibilidad(Part-time)"))
    clausses.append(aima3.utils.expr("Disponibilidad(Full-time)"))
    clausses.append(aima3.utils.expr("Disponibilidad(Freelance)"))
    #-------------------
    clausses.append(aima3.utils.expr("TrabajoenEquipo(Lider)"))
    clausses.append(aima3.utils.expr("TrabajoenEquipo(Referente)"))
    clausses.append(aima3.utils.expr("TrabajoenEquipo(Colaborador)"))
    #-------------------
    clausses.append(aima3.utils.expr("CoordinacionEquipos(Colaborador)"))
    clausses.append(aima3.utils.expr("CoordinacionEquipos(Lider)"))
    #-------------------
    clausses.append(aima3.utils.expr("Optimizaciones(Cpu)"))
    clausses.append(aima3.utils.expr("Optimizaciones(Memoria)"))
    clausses.append(aima3.utils.expr("Optimizaciones(Disco)"))
    clausses.append(aima3.utils.expr("Optimizaciones(Navegador)"))
    #-------------------
    clausses.append(aima3.utils.expr("browser(Firefox)"))
    clausses.append(aima3.utils.expr("browser(Chrome)"))
    clausses.append(aima3.utils.expr("browser(Safari)"))
    #-------------------
    clausses.append(aima3.utils.expr("OptimizaOrientacion(Cpu,BackEnd)"))
    clausses.append(aima3.utils.expr("OptimizaOrientacion(Memoria,FrontEnd)"))
    clausses.append(aima3.utils.expr("OptimizaOrientacion(Navegador,FrontEnd)"))
    clausses.append(aima3.utils.expr("OptimizaOrientacion(Disco,BackEnd)"))
    clausses.append(aima3.utils.expr("OptimizaOrientacion(Cpu,Dba)"))
    #-------------------
    clausses.append(aima3.utils.expr("Sueldo(Bajo)"))
    clausses.append(aima3.utils.expr("Sueldo(Medio)"))
    clausses.append(aima3.utils.expr("Sueldo(Alto)"))
    #-------------------
    clausses.append(aima3.utils.expr("Arquitectura(Cloud)"))
    clausses.append(aima3.utils.expr("Arquitectura(Ondemand)"))

    return clausses