import aima3.utils
import aima3.logic
from aima3.logic import pl_resolution


def getClauses():
    clauses = []


    # clausulas del usuario a BC


    clauses.append(aima3.utils.expr("Lenguaje(x) ==> LengUser(x)"))
    clauses.append(aima3.utils.expr("Framework(x) ==> FrameUser(x)"))
    clauses.append(aima3.utils.expr("Experiencia(x) ==> ExpLengUser(x)"))
    clauses.append(aima3.utils.expr("Experiencia(x) ==> ExpFrameUser(x)"))







    clauses.append(aima3.utils.expr("Orientacionuser(Frontend) & ExpFrameUser(Junior) ==> Puesto(Frontend)"))
    clauses.append(aima3.utils.expr("Puesto(Backend)"))
    clauses.append(aima3.utils.expr("Puesto(Fullstack)"))
    clauses.append(aima3.utils.expr("Puesto(DBA)"))
    clauses.append(aima3.utils.expr("Puesto(TeamLeader)"))
    clauses.append(aima3.utils.expr("Puesto(SoftwareEngineerManager)"))
    clauses.append(aima3.utils.expr("Puesto(ChiefTechnologyOfficer)"))
    clauses.append(aima3.utils.expr("Puesto(CTO)"))

    #-------------------

    clauses.append(aima3.utils.expr("Lenguaje(Python)"))
    clauses.append(aima3.utils.expr("Lenguaje(Java)"))
    # clauses.append(aima3.utils.expr("Lenguaje(C++)"))
    clauses.append(aima3.utils.expr("Lenguaje(Ruby)"))
    clauses.append(aima3.utils.expr("Lenguaje(Swift)"))
    clauses.append(aima3.utils.expr("Lenguaje(Go)"))
    clauses.append(aima3.utils.expr("Lenguaje(Rust)"))
    clauses.append(aima3.utils.expr("Lenguaje(PHP)"))
    clauses.append(aima3.utils.expr("Lenguaje(Haskell)"))
    # clauses.append(aima3.utils.expr("Lenguaje(C#)"))
    clauses.append(aima3.utils.expr("Lenguaje(Perl)"))
    clauses.append(aima3.utils.expr("Lenguaje(Objective-C)"))
    clauses.append(aima3.utils.expr("Lenguaje(Kotlin)"))
    clauses.append(aima3.utils.expr("Lenguaje(Scala)"))
    clauses.append(aima3.utils.expr("Lenguaje(R)"))
    clauses.append(aima3.utils.expr("Lenguaje(Lua)"))
    clauses.append(aima3.utils.expr("Lenguaje(Matlab)"))
    clauses.append(aima3.utils.expr("Lenguaje(Groovy)"))
    clauses.append(aima3.utils.expr("Lenguaje(Clojure)"))
    clauses.append(aima3.utils.expr("Lenguaje(Shell)"))
    clauses.append(aima3.utils.expr("Lenguaje(Assembly)"))
    # clauses.append(aima3.utils.expr("Lenguaje(F#)"))
    clauses.append(aima3.utils.expr("Lenguaje(Elixir)"))
    clauses.append(aima3.utils.expr("Lenguaje(Julia)"))
    clauses.append(aima3.utils.expr("Lenguaje(Racket)"))
    clauses.append(aima3.utils.expr("Lenguaje(Fortran)"))
    # clauses.append(aima3.utils.expr("Lenguaje(VB.NET)"))
    # clauses.append(aima3.utils.expr("Lenguaje(.Net)"))
    clauses.append(aima3.utils.expr("Lenguaje(JavaScript)"))
    clauses.append(aima3.utils.expr("Lenguaje(TypeScript)"))
    clauses.append(aima3.utils.expr("Lenguaje(HTML)"))
    clauses.append(aima3.utils.expr("Lenguaje(CSS)"))
    clauses.append(aima3.utils.expr("Lenguaje(Dart)"))
    clauses.append(aima3.utils.expr("Lenguaje(MySQL)"))
    clauses.append(aima3.utils.expr("Lenguaje(MongoDB)"))
    clauses.append(aima3.utils.expr("Lenguaje(MariaDB)"))
    clauses.append(aima3.utils.expr("Lenguaje(Sql)"))

    clauses.append(aima3.utils.expr("Framework(React)"))
    clauses.append(aima3.utils.expr("Framework(Angular)"))
    # clauses.append(aima3.utils.expr("Framework(Vue.js)"))
    clauses.append(aima3.utils.expr("Framework(Django)"))
    clauses.append(aima3.utils.expr("Framework(RubyonRails)"))
    clauses.append(aima3.utils.expr("Framework(Laravel)"))
    clauses.append(aima3.utils.expr("Framework(Spring)"))
    # clauses.append(aima3.utils.expr("Framework(Express.js)"))
    # clauses.append(aima3.utils.expr("Framework(ASP.NET)"))
    clauses.append(aima3.utils.expr("Framework(Flask)"))
    clauses.append(aima3.utils.expr("Framework(Symfony)"))
    # clauses.append(aima3.utils.expr("Framework(ASP.NETCore)"))
    clauses.append(aima3.utils.expr("Framework(Flutter)"))
    # clauses.append(aima3.utils.expr("Framework(Ember.js)"))
    # clauses.append(aima3.utils.expr("Framework(Xamarin)"))
    # clauses.append(aima3.utils.expr("Framework(Backbone.js)"))
    clauses.append(aima3.utils.expr("Framework(Meteor)"))
    clauses.append(aima3.utils.expr("Framework(PlayFramework)"))
    clauses.append(aima3.utils.expr("Framework(CakePHP)"))
    clauses.append(aima3.utils.expr("Framework(CodeIgniter)"))
    clauses.append(aima3.utils.expr("Framework(PlayFramework)"))
    clauses.append(aima3.utils.expr("Framework(Angular)"))
    # clauses.append(aima3.utils.expr("Framework(Express.js)"))
    # clauses.append(aima3.utils.expr("Framework(ASP.NET)"))


    clauses.append(aima3.utils.expr("Utiliza(Angular,JavaScript)"))
    clauses.append(aima3.utils.expr("Utiliza(Angular,TypeScript)"))
    # clauses.append(aima3.utils.expr("Utiliza(ASP.NET,C#)"))
    # clauses.append(aima3.utils.expr("Utiliza(ASP.NET,VB.NET)"))
    # clauses.append(aima3.utils.expr("Utiliza(ASP.NETCore,C#)"))
    # clauses.append(aima3.utils.expr("Utiliza(Backbone.js,JavaScript)"))
    clauses.append(aima3.utils.expr("Utiliza(CakePHP,PHP)"))
    clauses.append(aima3.utils.expr("Utiliza(CodeIgniter,PHP)"))
    clauses.append(aima3.utils.expr("Utiliza(Django,Python)"))
    # clauses.append(aima3.utils.expr("Utiliza(Ember.js,JavaScript)"))
    # clauses.append(aima3.utils.expr("Utiliza(Express.js,JavaScript)"))
    # clauses.append(aima3.utils.expr("Utiliza(Express.js,Node.js)"))
    clauses.append(aima3.utils.expr("Utiliza(Flask,Python)"))
    clauses.append(aima3.utils.expr("Utiliza(Flutter,Dart)"))
    clauses.append(aima3.utils.expr("Utiliza(Laravel,PHP)"))
    clauses.append(aima3.utils.expr("Utiliza(Meteor,JavaScript)"))
    clauses.append(aima3.utils.expr("Utiliza(PlayFramework,Java)"))
    clauses.append(aima3.utils.expr("Utiliza(PlayFramework,Scala)"))
    clauses.append(aima3.utils.expr("Utiliza(React,JavaScript)"))
    clauses.append(aima3.utils.expr("Utiliza(RubyonRails,Ruby)"))
    clauses.append(aima3.utils.expr("Utiliza(Spring,Java)"))
    clauses.append(aima3.utils.expr("Utiliza(Symfony,PHP)"))
    # clauses.append(aima3.utils.expr("Utiliza(Vue.js,JavaScript)"))
    # clauses.append(aima3.utils.expr("Utiliza(Xamarin,C#)"))




    clauses.append(aima3.utils.expr("Orientacion(Backend)"))
    clauses.append(aima3.utils.expr("Orientacion(Frontend)"))
    clauses.append(aima3.utils.expr("Orientacion(Dba)"))

    clauses.append(aima3.utils.expr("LengOrientado(Python,Backend)"))
    clauses.append(aima3.utils.expr("LengOrientado(Java,Backend)"))
    # clauses.append(aima3.utils.expr("LengOrientado(C++,Backend)"))
    clauses.append(aima3.utils.expr("LengOrientado(Ruby,Backend)"))
    clauses.append(aima3.utils.expr("LengOrientado(Swift,Backend)"))
    clauses.append(aima3.utils.expr("LengOrientado(Go,Backend)"))
    clauses.append(aima3.utils.expr("LengOrientado(Rust,Backend)"))
    clauses.append(aima3.utils.expr("LengOrientado(PHP,Backend)"))
    clauses.append(aima3.utils.expr("LengOrientado(Haskell,Backend)"))
    # clauses.append(aima3.utils.expr("LengOrientado(C#,Backend)"))
    clauses.append(aima3.utils.expr("LengOrientado(Perl,Backend)"))
    clauses.append(aima3.utils.expr("LengOrientado(Objective-C,Backend)"))
    clauses.append(aima3.utils.expr("LengOrientado(Kotlin,Backend)"))
    clauses.append(aima3.utils.expr("LengOrientado(Scala,Backend)"))
    clauses.append(aima3.utils.expr("LengOrientado(R,Backend)"))
    clauses.append(aima3.utils.expr("LengOrientado(Lua,Backend)"))
    clauses.append(aima3.utils.expr("LengOrientado(Matlab,Backend)"))
    clauses.append(aima3.utils.expr("LengOrientado(Groovy,Backend)"))
    clauses.append(aima3.utils.expr("LengOrientado(Clojure,Backend)"))
    clauses.append(aima3.utils.expr("LengOrientado(Shell,Backend)"))
    clauses.append(aima3.utils.expr("LengOrientado(MySQL,Backend)"))
    clauses.append(aima3.utils.expr("LengOrientado(MongoDB,Backend)"))
    clauses.append(aima3.utils.expr("LengOrientado(mariaDB,Backend)"))
    clauses.append(aima3.utils.expr("LengOrientado(Sql,Backend)"))

    clauses.append(aima3.utils.expr("LengOrientado(Assembly,Backend)"))
    # clauses.append(aima3.utils.expr("LengOrientado(F#,Backend)"))
    clauses.append(aima3.utils.expr("LengOrientado(Elixir,Backend)"))
    clauses.append(aima3.utils.expr("LengOrientado(Julia,Backend)"))
    clauses.append(aima3.utils.expr("LengOrientado(Racket,Backend)"))
    clauses.append(aima3.utils.expr("LengOrientado(Fortran,Backend)"))
    # clauses.append(aima3.utils.expr("LengOrientado(VB.NET,Backend)"))
    # clauses.append(aima3.utils.expr("LengOrientado(.Net,Backend)"))
    clauses.append(aima3.utils.expr("LengOrientado(JavaScript,Frontend)"))
    clauses.append(aima3.utils.expr("LengOrientado(TypeScript,Frontend)"))
    clauses.append(aima3.utils.expr("LengOrientado(HTML,Frontend)"))
    clauses.append(aima3.utils.expr("LengOrientado(CSS,Frontend)"))
    clauses.append(aima3.utils.expr("LengOrientado(Dart,Frontend)"))

    clauses.append(aima3.utils.expr("Pais(EstadosUnidos)"))
    clauses.append(aima3.utils.expr("Pais(Argentina)"))
    clauses.append(aima3.utils.expr("Pais(Brasil)"))
    clauses.append(aima3.utils.expr("Pais(Uruguay)"))
    clauses.append(aima3.utils.expr("Pais(Paraguay)"))
    clauses.append(aima3.utils.expr("Pais(Chile)"))
    clauses.append(aima3.utils.expr("Pais(Bolivia)"))
    clauses.append(aima3.utils.expr("Pais(México)"))
    clauses.append(aima3.utils.expr("Pais(Inglaterra)"))
    clauses.append(aima3.utils.expr("Pais(Francia)"))
    clauses.append(aima3.utils.expr("Pais(Alemania)"))

    clauses.append(aima3.utils.expr("Ciudad(Berlín)"))
    clauses.append(aima3.utils.expr("Ciudad(Múnich)"))
    clauses.append(aima3.utils.expr("Ciudad(Hamburgo)"))
    clauses.append(aima3.utils.expr("Ciudad(Fráncfort)"))
    clauses.append(aima3.utils.expr("Ciudad(Colonia)"))
    clauses.append(aima3.utils.expr("Ciudad(BuenosAires)"))
    clauses.append(aima3.utils.expr("Ciudad(Córdoba)"))
    clauses.append(aima3.utils.expr("Ciudad(Rosario)"))
    clauses.append(aima3.utils.expr("Ciudad(Mendoza)"))
    clauses.append(aima3.utils.expr("Ciudad(MardelPlata)"))
    clauses.append(aima3.utils.expr("Ciudad(LaPaz)"))
    clauses.append(aima3.utils.expr("Ciudad(SantaCruzdelaSierra)"))
    clauses.append(aima3.utils.expr("Ciudad(Cochabamba)"))
    clauses.append(aima3.utils.expr("Ciudad(Sucre)"))
    clauses.append(aima3.utils.expr("Ciudad(Potosí)"))
    clauses.append(aima3.utils.expr("Ciudad(SãoPaulo)"))
    clauses.append(aima3.utils.expr("Ciudad(RíodeJaneiro)"))
    clauses.append(aima3.utils.expr("Ciudad(Brasilia)"))
    clauses.append(aima3.utils.expr("Ciudad(Salvador)"))
    clauses.append(aima3.utils.expr("Ciudad(BeloHorizonte)"))
    clauses.append(aima3.utils.expr("Ciudad(Santiago)"))
    clauses.append(aima3.utils.expr("Ciudad(Valparaíso)"))
    clauses.append(aima3.utils.expr("Ciudad(ViñadelMar)"))
    clauses.append(aima3.utils.expr("Ciudad(Concepción)"))
    clauses.append(aima3.utils.expr("Ciudad(LaSerena)"))
    clauses.append(aima3.utils.expr("Ciudad(NuevaYork)"))
    clauses.append(aima3.utils.expr("Ciudad(LosÁngeles)"))
    clauses.append(aima3.utils.expr("Ciudad(Chicago)"))
    clauses.append(aima3.utils.expr("Ciudad(Miami)"))
    clauses.append(aima3.utils.expr("Ciudad(SanFrancisco)"))
    clauses.append(aima3.utils.expr("Ciudad(Paris)"))
    clauses.append(aima3.utils.expr("Ciudad(Marsella)"))
    clauses.append(aima3.utils.expr("Ciudad(Lyon)"))
    clauses.append(aima3.utils.expr("Ciudad(Toulouse)"))
    clauses.append(aima3.utils.expr("Ciudad(Niza)"))
    clauses.append(aima3.utils.expr("Ciudad(Londres)"))
    clauses.append(aima3.utils.expr("Ciudad(Manchester)"))
    clauses.append(aima3.utils.expr("Ciudad(Birmingham)"))
    clauses.append(aima3.utils.expr("Ciudad(Liverpool)"))
    clauses.append(aima3.utils.expr("Ciudad(Bristol)"))
    clauses.append(aima3.utils.expr("Ciudad(CiudaddeMéxico)"))
    clauses.append(aima3.utils.expr("Ciudad(Cancún)"))
    clauses.append(aima3.utils.expr("Ciudad(Guadalajara)"))
    clauses.append(aima3.utils.expr("Ciudad(Monterrey)"))
    clauses.append(aima3.utils.expr("Ciudad(Tijuana)"))
    clauses.append(aima3.utils.expr("Ciudad(Asunción)"))
    clauses.append(aima3.utils.expr("Ciudad(CiudaddelEste)"))
    clauses.append(aima3.utils.expr("Ciudad(Encarnación)"))
    clauses.append(aima3.utils.expr("Ciudad(Luque)"))
    clauses.append(aima3.utils.expr("Ciudad(SanLorenzo)"))
    clauses.append(aima3.utils.expr("Ciudad(Montevideo)"))
    clauses.append(aima3.utils.expr("Ciudad(PuntadelEste)"))
    clauses.append(aima3.utils.expr("Ciudad(ColoniadelSacramento)"))
    clauses.append(aima3.utils.expr("Ciudad(Salto)"))
    clauses.append(aima3.utils.expr("Ciudad(Piriápolis)"))

    clauses.append(aima3.utils.expr("CiudadPais(Berlín,Alemania)"))
    clauses.append(aima3.utils.expr("CiudadPais(Múnich,Alemania)"))
    clauses.append(aima3.utils.expr("CiudadPais(Hamburgo,Alemania)"))
    clauses.append(aima3.utils.expr("CiudadPais(Fráncfort,Alemania)"))
    clauses.append(aima3.utils.expr("CiudadPais(Colonia,Alemania)"))
    clauses.append(aima3.utils.expr("CiudadPais(BuenosAires,Argentina)"))
    clauses.append(aima3.utils.expr("CiudadPais(Córdoba,Argentina)"))
    clauses.append(aima3.utils.expr("CiudadPais(Rosario,Argentina)"))
    clauses.append(aima3.utils.expr("CiudadPais(Mendoza,Argentina)"))
    clauses.append(aima3.utils.expr("CiudadPais(MardelPlata,Argentina)"))
    clauses.append(aima3.utils.expr("CiudadPais(LaPaz,Bolivia)"))
    clauses.append(aima3.utils.expr("CiudadPais(SantaCruzdelaSierra,Bolivia)"))
    clauses.append(aima3.utils.expr("CiudadPais(Cochabamba,Bolivia)"))
    clauses.append(aima3.utils.expr("CiudadPais(Sucre,Bolivia)"))
    clauses.append(aima3.utils.expr("CiudadPais(Potosí,Bolivia)"))
    clauses.append(aima3.utils.expr("CiudadPais(SãoPaulo,Brasil)"))
    clauses.append(aima3.utils.expr("CiudadPais(RíodeJaneiro,Brasil)"))
    clauses.append(aima3.utils.expr("CiudadPais(Brasilia,Brasil)"))
    clauses.append(aima3.utils.expr("CiudadPais(Salvador,Brasil)"))
    clauses.append(aima3.utils.expr("CiudadPais(BeloHorizonte,Brasil)"))
    clauses.append(aima3.utils.expr("CiudadPais(Santiago,Chile)"))
    clauses.append(aima3.utils.expr("CiudadPais(Valparaíso,Chile)"))
    clauses.append(aima3.utils.expr("CiudadPais(ViñadelMar,Chile)"))
    clauses.append(aima3.utils.expr("CiudadPais(Concepción,Chile)"))
    clauses.append(aima3.utils.expr("CiudadPais(LaSerena,Chile)"))
    clauses.append(aima3.utils.expr("CiudadPais(NuevaYork,EstadosUnidos)"))
    clauses.append(aima3.utils.expr("CiudadPais(LosÁngeles,EstadosUnidos)"))
    clauses.append(aima3.utils.expr("CiudadPais(Chicago,EstadosUnidos)"))
    clauses.append(aima3.utils.expr("CiudadPais(Miami,EstadosUnidos)"))
    clauses.append(aima3.utils.expr("CiudadPais(SanFrancisco,EstadosUnidos)"))
    clauses.append(aima3.utils.expr("CiudadPais(Paris,Francia)"))
    clauses.append(aima3.utils.expr("CiudadPais(Marsella,Francia)"))
    clauses.append(aima3.utils.expr("CiudadPais(Lyon,Francia)"))
    clauses.append(aima3.utils.expr("CiudadPais(Toulouse,Francia)"))
    clauses.append(aima3.utils.expr("CiudadPais(Niza,Francia)"))
    clauses.append(aima3.utils.expr("CiudadPais(Londres,Inglaterra)"))
    clauses.append(aima3.utils.expr("CiudadPais(Manchester,Inglaterra)"))
    clauses.append(aima3.utils.expr("CiudadPais(Birmingham,Inglaterra)"))
    clauses.append(aima3.utils.expr("CiudadPais(Liverpool,Inglaterra)"))
    clauses.append(aima3.utils.expr("CiudadPais(Bristol,Inglaterra)"))
    clauses.append(aima3.utils.expr("CiudadPais(CiudaddeMéxico,Mexico)"))
    clauses.append(aima3.utils.expr("CiudadPais(Cancún,Mexico)"))
    clauses.append(aima3.utils.expr("CiudadPais(Guadalajara,Mexico)"))
    clauses.append(aima3.utils.expr("CiudadPais(Monterrey,Mexico)"))
    clauses.append(aima3.utils.expr("CiudadPais(Tijuana,Mexico)"))
    clauses.append(aima3.utils.expr("CiudadPais(Asunción,Paraguay)"))
    clauses.append(aima3.utils.expr("CiudadPais(CiudaddelEste,Paraguay)"))
    clauses.append(aima3.utils.expr("CiudadPais(Encarnación,Paraguay)"))
    clauses.append(aima3.utils.expr("CiudadPais(Luque,Paraguay)"))
    clauses.append(aima3.utils.expr("CiudadPais(SanLorenzo,Paraguay)"))
    clauses.append(aima3.utils.expr("CiudadPais(Montevideo,Uruguay)"))
    clauses.append(aima3.utils.expr("CiudadPais(PuntadelEste,Uruguay)"))
    clauses.append(aima3.utils.expr("CiudadPais(ColoniadelSacramento,Uruguay)"))
    clauses.append(aima3.utils.expr("CiudadPais(Salto,Uruguay)"))
    clauses.append(aima3.utils.expr("CiudadPais(Piriápolis,Uruguay)"))

    clauses.append(aima3.utils.expr("Experiencia(Senior)"))
    clauses.append(aima3.utils.expr("Experiencia(Semi-senior)"))
    clauses.append(aima3.utils.expr("Experiencia(Junior)"))
    clauses.append(aima3.utils.expr("Experiencia(Pasante)"))

    clauses.append(aima3.utils.expr("Idioma(Inglés)"))
    clauses.append(aima3.utils.expr("Idioma(Español)"))
    clauses.append(aima3.utils.expr("Idioma(Italiano)"))
    clauses.append(aima3.utils.expr("Idioma(Portugués)"))
    clauses.append(aima3.utils.expr("Idioma(Francés)"))
    clauses.append(aima3.utils.expr("Idioma(Alemán)"))

    clauses.append(aima3.utils.expr("Modalidad(Presencial)"))
    clauses.append(aima3.utils.expr("Modalidad(Virtual)"))
    clauses.append(aima3.utils.expr("Modalidad(Mixta)"))

    clauses.append(aima3.utils.expr("Disponibilidad(Part-time)"))
    clauses.append(aima3.utils.expr("Disponibilidad(Full-time)"))
    clauses.append(aima3.utils.expr("Disponibilidad(Freelance)"))

    clauses.append(aima3.utils.expr("TrabajoenEquipo(Lider)"))
    clauses.append(aima3.utils.expr("TrabajoenEquipo(Referente)"))
    clauses.append(aima3.utils.expr("TrabajoenEquipo(Colaborador)"))

    clauses.append(aima3.utils.expr("CoordinacionEquipos(Colaborador)"))
    clauses.append(aima3.utils.expr("CoordinacionEquipos(Lider)"))

    clauses.append(aima3.utils.expr("Optimizaciones(Cpu)"))
    clauses.append(aima3.utils.expr("Optimizaciones(Memoria)"))
    clauses.append(aima3.utils.expr("Optimizaciones(Disco)"))
    clauses.append(aima3.utils.expr("Optimizaciones(Navegador)"))

    clauses.append(aima3.utils.expr("browser(Firefox)"))
    clauses.append(aima3.utils.expr("browser(Chrome)"))
    clauses.append(aima3.utils.expr("browser(Safari)"))



    clauses.append(aima3.utils.expr("OptimizaOrientacion(Cpu,BackEnd)"))
    clauses.append(aima3.utils.expr("OptimizaOrientacion(Memoria,FrontEnd)"))
    clauses.append(aima3.utils.expr("OptimizaOrientacion(Navegador,FrontEnd)"))
    clauses.append(aima3.utils.expr("OptimizaOrientacion(Disco,BackEnd)"))
    clauses.append(aima3.utils.expr("OptimizaOrientacion(Cpu,Dba)"))

    clauses.append(aima3.utils.expr("Sueldo(Bajo)"))
    clauses.append(aima3.utils.expr("Sueldo(Medio)"))
    clauses.append(aima3.utils.expr("Sueldo(Alto)"))

    clauses.append(aima3.utils.expr("Arquitectura(Cloud)"))
    clauses.append(aima3.utils.expr("Arquitectura(Ondemand)"))




    return clauses


def initKB():
    KB = aima3.logic.FolKB(getClauses())
    return KB


if __name__ == '__main__':
    KB = initKB()

    consulta = aima3.utils.expr("LengUser(Java)")
    #La afirmación es falsa(no esta explicita en la BC). KB.ask = {v_5: Java}

    #consulta = aima3.utils.expr("LengUser(Pepe)")
    #La afirmación es falsa.(no esta explicita en la BC) KB.ask = False ( no se deduce de las reglas)


    if pl_resolution(KB, consulta):
        print("Esta en la BC")
    else:
        print("No esta en la BC")

    print("KB.ask= ", KB.ask(consulta))
    print(KB.ask(aima3.utils.expr('LengUser(Pepe)')))
