import aima3.utils
import aima3.logic


def getClauses():
    clauses = []

    # clausulas del usuario a BC

    clauses.append(aima3.utils.expr("LengUser(x)==> Lenguaje(x)"))
    clauses.append(aima3.utils.expr("FrameUser(x)==> Framework(x)"))


    clauses.append(aima3.utils.expr("Lenguaje(Python)"))
    clauses.append(aima3.utils.expr("Lenguaje(Java)"))
    #clauses.append(aima3.utils.expr("Lenguaje(C++)"))
    clauses.append(aima3.utils.expr("Lenguaje(Ruby)"))
    clauses.append(aima3.utils.expr("Lenguaje(Swift)"))
    clauses.append(aima3.utils.expr("Lenguaje(Go)"))
    clauses.append(aima3.utils.expr("Lenguaje(Rust)"))
    clauses.append(aima3.utils.expr("Lenguaje(PHP)"))
    clauses.append(aima3.utils.expr("Lenguaje(Haskell)"))
    #clauses.append(aima3.utils.expr("Lenguaje(C#)"))
    clauses.append(aima3.utils.expr("Lenguaje(Perl)"))
    clauses.append(aima3.utils.expr("Lenguaje(Objective-C)"))
    clauses.append(aima3.utils.expr("Lenguaje(Kotlin)"))
    clauses.append(aima3.utils.expr("Lenguaje(Scala)"))
    clauses.append(aima3.utils.expr("Lenguaje(R)"))
    clauses.append(aima3.utils.expr("Lenguaje(Lua)"))
    clauses.append(aima3.utils.expr("Lenguaje(Matlab)"))
    clauses.append(aima3.utils.expr("Lenguaje(Groovy)"))
    clauses.append(aima3.utils.expr("Lenguaje(Clojure)"))
    clauses.append(aima3.utils.expr("Lenguaje(Shell)"))
    clauses.append(aima3.utils.expr("Lenguaje(SQL)"))
    clauses.append(aima3.utils.expr("Lenguaje(Assembly)"))
    #clauses.append(aima3.utils.expr("Lenguaje(F#)"))
    clauses.append(aima3.utils.expr("Lenguaje(Elixir)"))
    clauses.append(aima3.utils.expr("Lenguaje(Julia)"))
    clauses.append(aima3.utils.expr("Lenguaje(Racket)"))
    clauses.append(aima3.utils.expr("Lenguaje(Fortran)"))
    #clauses.append(aima3.utils.expr("Lenguaje(VB.NET)"))
    #clauses.append(aima3.utils.expr("Lenguaje(.Net)"))
    clauses.append(aima3.utils.expr("Lenguaje(JavaScript)"))
    clauses.append(aima3.utils.expr("Lenguaje(TypeScript)"))
    clauses.append(aima3.utils.expr("Lenguaje(HTML)"))
    clauses.append(aima3.utils.expr("Lenguaje(CSS)"))
    clauses.append(aima3.utils.expr("Lenguaje(Dart)"))

    clauses.append(aima3.utils.expr("Framework(React)"))
    clauses.append(aima3.utils.expr("Framework(Angular)"))
    # clauses.append(aima3.utils.expr("Framework(Vue.js)"))
    clauses.append(aima3.utils.expr("Framework(Django)"))
    clauses.append(aima3.utils.expr("Framework(RubyonRails)"))
    clauses.append(aima3.utils.expr("Framework(Laravel)"))
    clauses.append(aima3.utils.expr("Framework(Spring)"))
    # clauses.append(aima3.utils.expr("Framework(Express.js)"))
    # clauses.append(aima3.utils.expr("Framework(ASP.NET)"))
    clauses.append(aima3.utils.expr("Framework(Flask)"))
    clauses.append(aima3.utils.expr("Framework(Symfony)"))
    # clauses.append(aima3.utils.expr("Framework(ASP.NETCore)"))
    clauses.append(aima3.utils.expr("Framework(Flutter)"))
    # clauses.append(aima3.utils.expr("Framework(Ember.js)"))
    # clauses.append(aima3.utils.expr("Framework(Xamarin)"))
    # clauses.append(aima3.utils.expr("Framework(Backbone.js)"))
    clauses.append(aima3.utils.expr("Framework(Meteor)"))
    clauses.append(aima3.utils.expr("Framework(PlayFramework)"))
    clauses.append(aima3.utils.expr("Framework(CakePHP)"))
    clauses.append(aima3.utils.expr("Framework(CodeIgniter)"))
    clauses.append(aima3.utils.expr("Framework(PlayFramework)"))
    clauses.append(aima3.utils.expr("Framework(Angular)"))
    # clauses.append(aima3.utils.expr("Framework(Express.js)"))
    # clauses.append(aima3.utils.expr("Framework(ASP.NET)"))

    clauses.append(aima3.utils.expr("Framework(React)==>LengUser(JavaScript)"))
    clauses.append(aima3.utils.expr("Framework(Angular)==>LengUser(JavaScript)"))
    # clauses.append(aima3.utils.expr("Framework(Vue.js)==>LengUser(JavaScript)"))
    clauses.append(aima3.utils.expr("Framework(Django)==>LengUser(Python)"))
    clauses.append(aima3.utils.expr("Framework(RubyonRails)==>LengUser(Ruby)"))
    clauses.append(aima3.utils.expr("Framework(Laravel)==>LengUser(PHP)"))
    clauses.append(aima3.utils.expr("Framework(Spring)==>LengUser(Java)"))
    # clauses.append(aima3.utils.expr("Framework(Express.js)==>LengUser(JavaScript)"))
    # clauses.append(aima3.utils.expr("Framework(ASP.NET)==>LengUser(C#)"))
    clauses.append(aima3.utils.expr("Framework(Flask)==>LengUser(Python)"))
    clauses.append(aima3.utils.expr("Framework(Symfony)==>LengUser(PHP)"))
    # clauses.append(aima3.utils.expr("Framework(ASP.NETCore)==>LengUser(C#)"))
    clauses.append(aima3.utils.expr("Framework(Flutter)==>LengUser(Dart)"))
    # clauses.append(aima3.utils.expr("Framework(Ember.js)==>LengUser(JavaScript)"))
    # clauses.append(aima3.utils.expr("Framework(Xamarin)==>LengUser(C#)"))
    # clauses.append(aima3.utils.expr("Framework(Backbone.js)==>LengUser(JavaScript)"))
    clauses.append(aima3.utils.expr("Framework(Meteor)==>LengUser(JavaScript)"))
    clauses.append(aima3.utils.expr("Framework(PlayFramework)==>LengUser(Java)"))
    clauses.append(aima3.utils.expr("Framework(CakePHP)==>LengUser(PHP)"))
    clauses.append(aima3.utils.expr("Framework(CodeIgniter)==>LengUser(PHP)"))
    clauses.append(aima3.utils.expr("Framework(PlayFramework)==>LengUser(Scala)"))
    clauses.append(aima3.utils.expr("Framework(Angular)==>LengUser(JavaScript)"))
    # clauses.append(aima3.utils.expr("Framework(Express.js)==>LengUser(Node.js)"))
    # clauses.append(aima3.utils.expr("Framework(ASP.NET)==>LengUser(VB.NET)"))

    clauses.append(aima3.utils.expr("Lenguaje(Python)==> Lengorientado(Backend)"))
    clauses.append(aima3.utils.expr("Lenguaje(Java)==> Lengorientado(Backend)"))
    #clauses.append(aima3.utils.expr("Lenguaje(C++)==> Lengorientado(Backend)"))
    clauses.append(aima3.utils.expr("Lenguaje(Ruby)==> Lengorientado(Backend)"))
    clauses.append(aima3.utils.expr("Lenguaje(Swift)==> Lengorientado(Backend)"))
    clauses.append(aima3.utils.expr("Lenguaje(Go)==> Lengorientado(Backend)"))
    clauses.append(aima3.utils.expr("Lenguaje(Rust)==> Lengorientado(Backend)"))
    clauses.append(aima3.utils.expr("Lenguaje(PHP)==> Lengorientado(Backend)"))
    clauses.append(aima3.utils.expr("Lenguaje(Haskell)==> Lengorientado(Backend)"))
    #clauses.append(aima3.utils.expr("Lenguaje(C#)==> Lengorientado(Backend)"))
    clauses.append(aima3.utils.expr("Lenguaje(Perl)==> Lengorientado(Backend)"))
    clauses.append(aima3.utils.expr("Lenguaje(Objective-C)==> Lengorientado(Backend)"))
    clauses.append(aima3.utils.expr("Lenguaje(Kotlin)==> Lengorientado(Backend)"))
    clauses.append(aima3.utils.expr("Lenguaje(Scala)==> Lengorientado(Backend)"))
    clauses.append(aima3.utils.expr("Lenguaje(R)==> Lengorientado(Backend)"))
    clauses.append(aima3.utils.expr("Lenguaje(Lua)==> Lengorientado(Backend)"))
    clauses.append(aima3.utils.expr("Lenguaje(Matlab)==> Lengorientado(Backend)"))
    clauses.append(aima3.utils.expr("Lenguaje(Groovy)==> Lengorientado(Backend)"))
    clauses.append(aima3.utils.expr("Lenguaje(Clojure)==> Lengorientado(Backend)"))
    clauses.append(aima3.utils.expr("Lenguaje(Shell)==> Lengorientado(Backend)"))
    clauses.append(aima3.utils.expr("Lenguaje(SQL)==> Lengorientado(Backend)"))
    clauses.append(aima3.utils.expr("Lenguaje(Assembly)==> Lengorientado(Backend)"))
    #clauses.append(aima3.utils.expr("Lenguaje(F#)==> Lengorientado(Backend)"))
    clauses.append(aima3.utils.expr("Lenguaje(Elixir)==> Lengorientado(Backend)"))
    clauses.append(aima3.utils.expr("Lenguaje(Julia)==> Lengorientado(Backend)"))
    clauses.append(aima3.utils.expr("Lenguaje(Racket)==> Lengorientado(Backend)"))
    clauses.append(aima3.utils.expr("Lenguaje(Fortran)==> Lengorientado(Backend)"))
    #clauses.append(aima3.utils.expr("Lenguaje(VB.NET)==> Lengorientado(Backend)"))
   # clauses.append(aima3.utils.expr("Lenguaje(.Net)==> Lengorientado(Backend)"))
    clauses.append(aima3.utils.expr("Lenguaje(JavaScript)==> Lengorientado(Frontend)"))
    clauses.append(aima3.utils.expr("Lenguaje(TypeScript)==> Lengorientado(Frontend)"))
    clauses.append(aima3.utils.expr("Lenguaje(HTML)==> Lengorientado(Frontend)"))
    clauses.append(aima3.utils.expr("Lenguaje(CSS)==> Lengorientado(Frontend)"))
    clauses.append(aima3.utils.expr("Lenguaje(Dart)==> Lengorientado(Frontend)"))

    clauses.append(aima3.utils.expr("Pais(EstadosUnidos)"))
    clauses.append(aima3.utils.expr("Pais(Argentina)"))
    clauses.append(aima3.utils.expr("Pais(Brasil)"))
    clauses.append(aima3.utils.expr("Pais(Uruguay)"))
    clauses.append(aima3.utils.expr("Pais(Paraguay)"))
    clauses.append(aima3.utils.expr("Pais(Chile)"))
    clauses.append(aima3.utils.expr("Pais(Bolivia)"))
    clauses.append(aima3.utils.expr("Pais(México)"))
    clauses.append(aima3.utils.expr("Pais(Inglaterra)"))
    clauses.append(aima3.utils.expr("Pais(Francia)"))
    clauses.append(aima3.utils.expr("Pais(Alemania)"))

    clauses.append(aima3.utils.expr("Ciudad(Berlín)==> Pais(Alemania)"))
    clauses.append(aima3.utils.expr("Ciudad(Múnich)==> Pais(Alemania)"))
    clauses.append(aima3.utils.expr("Ciudad(Hamburgo)==> Pais(Alemania)"))
    clauses.append(aima3.utils.expr("Ciudad(Fráncfort)==> Pais(Alemania)"))
    clauses.append(aima3.utils.expr("Ciudad(Colonia)==> Pais(Alemania)"))
    clauses.append(aima3.utils.expr("Ciudad(BuenosAires)==> Pais(Argentina)"))
    clauses.append(aima3.utils.expr("Ciudad(Córdoba)==> Pais(Argentina)"))
    clauses.append(aima3.utils.expr("Ciudad(Rosario)==> Pais(Argentina)"))
    clauses.append(aima3.utils.expr("Ciudad(Mendoza)==> Pais(Argentina)"))
    clauses.append(aima3.utils.expr("Ciudad(MardelPlata)==> Pais(Argentina)"))
    clauses.append(aima3.utils.expr("Ciudad(LaPaz)==> Pais(Bolivia)"))
    clauses.append(aima3.utils.expr("Ciudad(SantaCruzdelaSierra)==> Pais(Bolivia)"))
    clauses.append(aima3.utils.expr("Ciudad(Cochabamba)==> Pais(Bolivia)"))
    clauses.append(aima3.utils.expr("Ciudad(Sucre)==> Pais(Bolivia)"))
    clauses.append(aima3.utils.expr("Ciudad(Potosí)==> Pais(Bolivia)"))
    clauses.append(aima3.utils.expr("Ciudad(SãoPaulo)==> Pais(Brasil)"))
    clauses.append(aima3.utils.expr("Ciudad(RíodeJaneiro)==> Pais(Brasil)"))
    clauses.append(aima3.utils.expr("Ciudad(Brasilia)==> Pais(Brasil)"))
    clauses.append(aima3.utils.expr("Ciudad(Salvador)==> Pais(Brasil)"))
    clauses.append(aima3.utils.expr("Ciudad(BeloHorizonte)==> Pais(Brasil)"))
    clauses.append(aima3.utils.expr("Ciudad(Santiago)==> Pais(Chile)"))
    clauses.append(aima3.utils.expr("Ciudad(Valparaíso)==> Pais(Chile)"))
    clauses.append(aima3.utils.expr("Ciudad(ViñadelMar)==> Pais(Chile)"))
    clauses.append(aima3.utils.expr("Ciudad(Concepción)==> Pais(Chile)"))
    clauses.append(aima3.utils.expr("Ciudad(LaSerena)==> Pais(Chile)"))
    clauses.append(aima3.utils.expr("Ciudad(NuevaYork)==> Pais(EstadosUnidos)"))
    clauses.append(aima3.utils.expr("Ciudad(LosÁngeles)==> Pais(EstadosUnidos)"))
    clauses.append(aima3.utils.expr("Ciudad(Chicago)==> Pais(EstadosUnidos)"))
    clauses.append(aima3.utils.expr("Ciudad(Miami)==> Pais(EstadosUnidos)"))
    clauses.append(aima3.utils.expr("Ciudad(SanFrancisco)==> Pais(EstadosUnidos)"))
    clauses.append(aima3.utils.expr("Ciudad(París)==> Pais(Francia)"))
    clauses.append(aima3.utils.expr("Ciudad(Marsella)==> Pais(Francia)"))
    clauses.append(aima3.utils.expr("Ciudad(Lyon)==> Pais(Francia)"))
    clauses.append(aima3.utils.expr("Ciudad(Toulouse)==> Pais(Francia)"))
    clauses.append(aima3.utils.expr("Ciudad(Niza)==> Pais(Francia)"))
    clauses.append(aima3.utils.expr("Ciudad(Londres)==> Pais(Inglaterra)"))
    clauses.append(aima3.utils.expr("Ciudad(Manchester)==> Pais(Inglaterra)"))
    clauses.append(aima3.utils.expr("Ciudad(Birmingham)==> Pais(Inglaterra)"))
    clauses.append(aima3.utils.expr("Ciudad(Liverpool)==> Pais(Inglaterra)"))
    clauses.append(aima3.utils.expr("Ciudad(Bristol)==> Pais(Inglaterra)"))
    clauses.append(aima3.utils.expr("Ciudad(CiudaddeMéxico)==> Pais(México)"))
    clauses.append(aima3.utils.expr("Ciudad(Cancún)==> Pais(México)"))
    clauses.append(aima3.utils.expr("Ciudad(Guadalajara)==> Pais(México)"))
    clauses.append(aima3.utils.expr("Ciudad(Monterrey)==> Pais(México)"))
    clauses.append(aima3.utils.expr("Ciudad(Tijuana)==> Pais(México)"))
    clauses.append(aima3.utils.expr("Ciudad(Asunción)==> Pais(Paraguay)"))
    clauses.append(aima3.utils.expr("Ciudad(CiudaddelEste)==> Pais(Paraguay)"))
    clauses.append(aima3.utils.expr("Ciudad(Encarnación)==> Pais(Paraguay)"))
    clauses.append(aima3.utils.expr("Ciudad(Luque)==> Pais(Paraguay)"))
    clauses.append(aima3.utils.expr("Ciudad(SanLorenzo)==> Pais(Paraguay)"))
    clauses.append(aima3.utils.expr("Ciudad(Montevideo)==> Pais(Uruguay)"))
    clauses.append(aima3.utils.expr("Ciudad(PuntadelEste)==> Pais(Uruguay)"))
    clauses.append(aima3.utils.expr("Ciudad(ColoniadelSacramento)==> Pais(Uruguay)"))
    clauses.append(aima3.utils.expr("Ciudad(Salto)==> Pais(Uruguay)"))
    clauses.append(aima3.utils.expr("Ciudad(Piriápolis)==> Pais(Uruguay)"))

    clauses.append(aima3.utils.expr("Puesto(Frontend)"))
    clauses.append(aima3.utils.expr("Puesto(Backend)"))
    clauses.append(aima3.utils.expr("Puesto(Fullstack)"))
    clauses.append(aima3.utils.expr("Puesto(DBA)"))
    clauses.append(aima3.utils.expr("Puesto(TeamLeader)"))
    clauses.append(aima3.utils.expr("Puesto(SoftwareEngineerManager)"))
    clauses.append(aima3.utils.expr("Puesto(ChiefTechnologyOfficer)"))
    clauses.append(aima3.utils.expr("Puesto(CTO)"))

    clauses.append(aima3.utils.expr("Experiencia(Senior)"))
    clauses.append(aima3.utils.expr("Experiencia(Semi-senior)"))
    clauses.append(aima3.utils.expr("Experiencia(Junior)"))
    clauses.append(aima3.utils.expr("Experiencia(Pasante)"))

    clauses.append(aima3.utils.expr("Idioma(Inglés)"))
    clauses.append(aima3.utils.expr("Idioma(Español)"))
    clauses.append(aima3.utils.expr("Idioma(Italiano)"))
    clauses.append(aima3.utils.expr("Idioma(Portugués)"))
    clauses.append(aima3.utils.expr("Idioma(Francés)"))
    clauses.append(aima3.utils.expr("Idioma(Alemán)"))

    clauses.append(aima3.utils.expr("Modalidad(Presencial)"))
    clauses.append(aima3.utils.expr("Modalidad(Virtual)"))
    clauses.append(aima3.utils.expr("Modalidad(Mixta)"))

    clauses.append(aima3.utils.expr("Disponibilidad(Part-time)"))
    clauses.append(aima3.utils.expr("Disponibilidad(Full-time)"))
    clauses.append(aima3.utils.expr("Disponibilidad(Freelance)"))





    #Clausulalas recopiladas con npl



    return clauses


def initKB():
    KB = aima3.logic.FolKB(getClauses())
    return KB


if __name__ == '__main__':
    KB = initKB()
    consulta1 = KB.ask(aima3.utils.expr('LengUser(JavaScript)'))
    consulta1 = KB.ask(aima3.utils.expr('FrameUser(Angular)'))
    print(consulta1)